// This file is generated by scripts/generateCatalogFromPublic.js
// Run: node scripts/generateCatalogFromPublic.js

export const generatedCatalog = [
  {
    "id": 1788358874311,
    "title": "Chevrolet Astra",
    "year": "",
    "price": "",
    "image": "/imagenes%20de%20los%20autos/chevrolet%20astra/chevriket%20astra.jpeg",
    "images": [
      "/imagenes%20de%20los%20autos/chevrolet%20astra/chevriket%20astra.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874312,
    "title": "Fiat Siena",
    "year": "",
    "price": "",
    "image": "/imagenes%20de%20los%20autos/fiat%20siena/fiat%20palio%202013%20full.jpeg",
    "images": [
      "/imagenes%20de%20los%20autos/fiat%20siena/fiat%20palio%202013%20full.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874313,
    "title": "Ford Explorer",
    "year": "",
    "price": "",
    "image": "/imagenes%20de%20los%20autos/ford%20explorer/baul%20explorer.jpeg",
    "images": [
      "/imagenes%20de%20los%20autos/ford%20explorer/baul%20explorer.jpeg",
      "/imagenes%20de%20los%20autos/ford%20explorer/costado%20izquierda%20explorer.jpeg",
      "/imagenes%20de%20los%20autos/ford%20explorer/costado%20izquierdaexplorer.jpeg",
      "/imagenes%20de%20los%20autos/ford%20explorer/Costado%20traserio%20explorer.jpeg",
      "/imagenes%20de%20los%20autos/ford%20explorer/frente%20de%20explorer.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874314,
    "title": "Partener Pagatonica",
    "year": "",
    "price": "",
    "image": "/imagenes%20de%20los%20autos/partener%20pagatonica/partner%20patagonica.jpeg",
    "images": [
      "/imagenes%20de%20los%20autos/partener%20pagatonica/partner%20patagonica.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874315,
    "title": "Volkswagen Up",
    "year": "",
    "price": "",
    "image": "/imagenes%20de%20los%20autos/volkswagen%20up/volkswagen%20up.jpeg",
    "images": [
      "/imagenes%20de%20los%20autos/volkswagen%20up/volkswagen%20up.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  }
];
