// This file is generated by scripts/generateCatalogFromPublic.js
// Run: node scripts/generateCatalogFromPublic.js

export const generatedCatalog = [
  {
    "id": 1788358874311,
    "title": "Chevrolet Astra",
    "year": "",
    "price": "",
    "image": "/file.svg",
    "images": ["/file.svg"],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874312,
    "title": "Fiat Siena",
    "year": "",
    "price": "",
    "image": "/siena%20frente.jpeg",
    "images": ["/siena%20frente.jpeg"],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874313,
    "title": "Ford Explorer",
    "year": "",
    "price": "",
    "image": "/frente%20ford%20explorer.jpeg",
    "images": [
      "/frente%20ford%20explorer.jpeg",
      "/lateral%20derecho%20ford%20explorer.jpeg",
      "/lateral%20izquierdo%20ford%20explorer.jpeg",
      "/baul%20ford%20explorer.jpeg"
    ],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874314,
    "title": "Partener Pagatonica",
    "year": "",
    "price": "",
    "image": "/file.svg",
    "images": ["/file.svg"],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  },
  {
    "id": 1788358874315,
    "title": "Volkswagen Up",
    "year": "",
    "price": "",
    "image": "/frente%20up.jpeg",
    "images": ["/frente%20up.jpeg"],
    "badge": "",
    "km": "",
    "fuel": "",
    "transmission": "",
    "description": ""
  }
];
