const fs = require('fs');
const path = require('path');

const publicDir = path.join(process.cwd(), 'public');
// Prefer scanning the common images folder if present
const preferredSubfolder = path.join(publicDir, 'imagenes de los autos');
const scanRoot = fs.existsSync(preferredSubfolder) ? preferredSubfolder : publicDir;
const outFile = path.join(process.cwd(), 'app', 'generated-catalog.ts');

function titleCase(str) {
  return str
    .replace(/[-_]/g, ' ')
    .split(' ')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ')
    .trim();
}

function encodeSegment(segment) {
  return encodeURIComponent(segment).replace(/%20/g, '%20');
}

const imageExtensions = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.bmp', '.svg']);

function isImage(filename) {
  return imageExtensions.has(path.extname(filename).toLowerCase());
}

function scan() {
  if (!fs.existsSync(publicDir)) {
    console.error('No existe el directorio public/');
    process.exit(1);
  }

  const items = fs.readdirSync(scanRoot, { withFileTypes: true });

  const folders = items.filter((it) => it.isDirectory()).map((d) => d.name);
  const rootPrefix = scanRoot === publicDir ? '' : '/' + encodeSegment(path.basename(scanRoot));

  const entries = [];

  let idCounter = Date.now();

  for (const folder of folders) {
    const folderPath = path.join(scanRoot, folder);
    const files = fs.readdirSync(folderPath).filter((f) => isImage(f));
    if (files.length === 0) continue;

    const encodedFolder = `${rootPrefix}/${encodeSegment(folder)}`;
    const images = files.map((f) => `${encodedFolder}/${encodeSegment(f)}`);
    const primary = images[0];

    const entry = {
      id: idCounter,
      title: titleCase(folder),
      year: '',
      price: '',
      image: primary,
      images: images,
      badge: '',
      km: '',
      fuel: '',
      transmission: '',
      description: '',
    };

    entries.push(entry);
    idCounter += 1;
  }

  return entries;
}

function write(entries) {
  const header = `// This file is generated by scripts/generateCatalogFromPublic.js\n// Run: node scripts/generateCatalogFromPublic.js\n\nexport const generatedCatalog = `;
  const body = JSON.stringify(entries, null, 2);
  const content = header + body + `;\n`;
  fs.writeFileSync(outFile, content, 'utf8');
  console.log('Wrote', outFile);
}

const entries = scan();
write(entries);

if (entries.length === 0) {
  console.log('No se encontraron carpetas con imágenes en public/');
} else {
  console.log('Generadas', entries.length, 'entradas.');
}
